services:
  pm2025-2-trabalho-final-mongo:
    image: mongo:7
    container_name: pm2025-2-trabalho-final-mongo
    restart: always
    command: ["mongod", "--auth", "--bind_ip_all"]
    environment:
      MONGO_HOST: pm2025-2-trabalho-final-mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: pm2025-2-mongo-admin
      MONGO_INITDB_ROOT_PASSWORD: pm2025-2-mongo-secret
      MONGO_INITDB_DATABASE: pm2025-2-mongodb
      MONGO_AUTH_SOURCE: admin
    ports:
      - ${MONGO_INITDB_PORT:-27017}:27017 
    volumes:
      - mongo_data:/data/db
      # Opcional: crie um user de aplicação automaticamente
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - pm2025-2-network

  pm2025-2-trabalho-final-portainer:
    image: portainer/portainer-ce:latest
    container_name: pm2025-2-trabalho-final-portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - pm2025-2-network

volumes:
  mongo_data:
  portainer_data:

networks:
  pm2025-2-network:
    driver: bridge
